[DOC] Add Quantile forest examples
neurodata/treeple pull request #147
Opened 2023-10-16 20:09 UTC by SUKI-O

Fixes #87 

Changes proposed in this pull request:

- Add examples to show how to use RandomForestRegressor class to genera quantile predictions.

## Before submitting

- [ ] I've read and followed all steps in the [Making a pull request](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [ ] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [ ] If this PR fixes a bug, I've added a test that will fail without my fix.
- [ ] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

## After submitting

- [ ] All GitHub Actions jobs for my pull request have passed.

2023-10-16 20:42 UTC, adam2392 commented
The 4 rendered artifacts: https://output.circle-artifacts.com/output/job/5db6e8d1-7cbe-4795-80d5-bbe5ab46dde6/artifacts/0/dev/use.html

@SUKI-O perhaps we can put this into its own section? I.e. `Quantile Predictions`? See the other example sections. This will help group the examples better.

2023-10-16 20:45 UTC, adam2392 requested changes
Great start and very encouraging that the simulations look very similar to those in `quantile-forests`. 

Can you try to break up each example to make them easier to read? 

For example, see the following example: https://output.circle-artifacts.com/output/job/5db6e8d1-7cbe-4795-80d5-bbe5ab46dde6/artifacts/0/dev/auto_examples/outlier_detection/plot_extended_isolation_forest.html#sphx-glr-auto-examples-outlier-detection-plot-extended-isolation-forest-py

In addition, perhaps we can be more explicit about what each example should show. What is the take-away message? E.g. in the right-skewed simulation, is it that QORF is better than standard ORF? What does better mean?

2023-10-16 20:45 UTC, adam2392 commented on examples/plot_quantile_interpolation_with_RF.py
> +print(__doc__)
Unnecessary

2023-10-16 20:45 UTC, adam2392 commented on examples/plot_quantile_regression_intervals_with_RF.py
> +print(__doc__)
Unnecessary

2023-10-16 20:45 UTC, adam2392 commented on examples/plot_quantile_vs_standard_oblique_forest.py
> +print(__doc__)
Unnecessary

2023-10-16 20:45 UTC, adam2392 commented on examples/plot_quantile_toy_example_with_RF.py
> +print(__doc__)
Unnecessary

2023-10-17 18:11 UTC, sampan501 requested changes
Looks good after removing the print statements that @adam2392 referenced

2023-10-18 18:41 UTC, adam2392 commented
https://output.circle-artifacts.com/output/job/eb2e193e-9f05-4d58-903b-41b9a7cf478c/artifacts/0/dev/use.html

I don't see the examples rendered now so there's probably an error in your change. You can leverage the development guide to build the docs locally for yourself to peruse.

2023-10-18 18:43 UTC, adam2392 commented
You are probably missing a section header which is rendered from the README files inside each subsection

2023-10-23 00:47 UTC, adam2392 requested changes
I know the examples are copied "as-is" from quantile-forests, but I think their documentation is not as comprehensive as I would've liked.

The examples could use a bit more explanation. WDYT @SUKI-O @sampan501 @PSSF23 ?

2023-10-23 00:47 UTC, adam2392 commented on doc/whats_new/v0.3.rst
> -* `Yuxin Bai`_
Can you un-revert this change?

2023-10-23 00:47 UTC, adam2392 commented on examples/quantile_predictions/README.txt
> +Examples demonstrating how to generate quantile predictions using RandomForest class.
```suggestion
Examples demonstrating how to generate quantile predictions using Random Forest variants.
```

2023-10-23 15:06 UTC, sampan501 requested changes
I think the only thing missing is a few comments about what exactly you are plotting and how to interpret the plots and we should be good to go

2023-10-23 15:06 UTC, sampan501 commented on examples/quantile_predictions/plot_quantile_interpolation_with_RF.py
> +
Maybe add a comment here describing what you are plotting, and a comment at the end explaining how to interpret the figure

2023-10-23 15:06 UTC, sampan501 commented on examples/quantile_predictions/plot_quantile_regression_intervals_with_RF.py
> +y_pred_interval = y_pred_upper - y_pred_lower
Same as above comment with regard to figures

2023-10-23 15:06 UTC, sampan501 commented on examples/quantile_predictions/plot_quantile_vs_standard_oblique_forest.py
> +colors = ["#c0c0c0", "#a6e5ff", "#e7a4f5"]
Same as above comment with regard to figures

2023-10-23 15:06 UTC, sampan501 commented on examples/quantile_predictions/plot_quantile_toy_example_with_RF.py
> +plt.plot(X_test, y_test, ".", c="#f2a619", label="Test Observations", ms=5)
Same as above comment with regard to figures

2023-10-24 14:02 UTC, adam2392 commented on examples/quantile_predictions/plot_quantile_vs_standard_oblique_forest.py
> +# Fit the model to the training samples
```suggestion
# Get the leaf-nodes the training samples fall into
```

2023-10-24 14:05 UTC, adam2392 commented on examples/quantile_predictions/plot_quantile_interpolation_with_RF.py
> +# To interpolate between the data points, i and j (i<=j),
```suggestion
# To interpolate between the data points, i and j (``i <= j``),
```

2023-10-24 14:06 UTC, adam2392 commented on examples/quantile_predictions/plot_quantile_interpolation_with_RF.py
> +# 5. nearest: i or j whichever is nearest.
```suggestion
# linear, lower, higher, midpoint, or nearest. For more details, see `sktree.RandomForestRegressor`.
```

2023-10-24 14:07 UTC, adam2392 requested changes
Few minor changes and then LGTM. 

Generally, it's useful to render the docs locally to see if there's any formatting issues.

Xref: https://output.circle-artifacts.com/output/job/b7f1c854-cb46-4c2d-8a79-57965fe88bd9/artifacts/0/dev/use.html#quantile-predictions-with-random-forest

2023-10-24 19:09 UTC, adam2392 approved these changes

2023-10-24 23:19 UTC, sampan501 approved these changes

2023-10-24 23:19 UTC, merged