MAINT Patch up trunk-classification and its usage with respect to parameters
neurodata/treeple pull request #227
Opened 2024-02-21 21:20 UTC by adam2392

Changes proposed in this pull request:
- if `trunk_mix`, mix should be required parameter
- if not `trunk_mix`, but mix is specified, there should be an error, else ppl could accidentally simulate trunk even though they intend on `trunk_mix` by specifying the mix parameter

## Before submitting

- [ ] I've read and followed all steps in the [Making a pull request](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [ ] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/py-why/pywhy-graphs/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [ ] If this PR fixes a bug, I've added a test that will fail without my fix.
- [ ] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

## After submitting

- [ ] All GitHub Actions jobs for my pull request have passed.

2024-02-21 21:20 UTC, adam2392 commented on sktree/datasets/hyppo.py
>          norm_params = [[mu_0, cov * (2 / 3) ** 2], [mu_1, cov * (2 / 3) ** 2]]
@sampan501 can you explain why we have a (2/3)**2 here and only in trunk-mix?

2024-02-21 22:49 UTC, sampan501 approved these changes

2024-02-21 22:49 UTC, sampan501 commented on sktree/datasets/hyppo.py
>          norm_params = [[mu_0, cov * (2 / 3) ** 2], [mu_1, cov * (2 / 3) ** 2]]
When variance is 1, trunk-mix does not look bimodal at low dimensions. I set it to (2/3)**2 since that is consistent with Marron and Wand bimodal

2024-02-22 03:35 UTC, YuxinB approved these changes

2024-02-22 12:59 UTC, sampan501 commented
@adam2392 Good to merge after changelog update

2024-02-23 16:11 UTC, adam2392 commented on sktree/datasets/hyppo.py
> +    )
@sampan501 can you explain what the role of `w` is? I'm not sure why it's passed via `mu_1`, or if it should be?

2024-02-23 17:27 UTC, sampan501 requested changes
Looks good! For simplicity, there is a lot of error checks that are common for all 3 functions. Maybe we can wrap those up into a private method?

2024-02-23 17:27 UTC, sampan501 commented
Other than that, pending CI, lgtm

2024-02-23 17:35 UTC, adam2392 commented
> Looks good! For simplicity, there is a lot of error checks that are common for all 3 functions. Maybe we can wrap those up into a private method?

Good idea. Rn tho there's only a few.  We could migrate the covariance matrix stuff to a `_default_covariance(...)` which handles the check and setting of covariance possibly. But maybe we can leave for later depending on any future added complexity. Otw over-engineering maybe :p

2024-02-23 17:50 UTC, sampan501 commented
Fair, I'll make an issue for it

2024-02-23 17:50 UTC, sampan501 approved these changes

2024-02-23 19:07 UTC, merged

2024-02-23 19:16 UTC, SUKI-O approved these changes

2024-02-23 20:42 UTC, YuxinB commented on sktree/datasets/hyppo.py
> +    )
From this code, if I understand right, w should be the probability that we sample from G. Like (1-w)*N(0,1)+w*G, G is any Marron-Wand simulation.