Rename the pkg to "treeple"
neurodata/treeple pull request #292
Opened 2024-07-07 19:39 UTC by SUKI-O

#### Reference Issues/PRs

Change the package name from `scikit-tree` to `treeple`

#### What does this implement/fix? Explain your changes.
* Replace `scikit-tree` to `treeple`
* Replace `sktree` to `treeple`
* Change the directory name `sktree` to `treeple`

#### Any other comments?
* The name of the repo itself in GH also need to be changed when ready
* After that, pypi has to be updated (I need help with this part)
* It builds locally using `spin` as expected.  
* When trying locally, I believe you have to re-initialize the submodule
```
git submodule init
git submodule update
```

2024-07-07 19:56 UTC, adam2392 commented
Mostly LGTM, but 

1. you'll need to fix the building of the documentation (https://app.circleci.com/pipelines/github/neurodata/scikit-tree/1741/workflows/345d4498-1b23-4ca7-8aaa-4dedf03eac94/jobs/2969?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary)
2. in the CHANGELOG entry, you should add a summary specifying the entire package was renamed. https://github.com/neurodata/scikit-tree/blob/98b67fcbaf028ee8a9bd92407089ab4a34008e9b/doc/whats_new/v0.9.rst?plain=1#L11
3. In the README, it would also be good to specify that in v0.9 and onwards, the package was renamed to treeple. <v0.8 is still installable via `scikit-tree` on pip.

2024-07-07 20:49 UTC, SUKI-O commented
@adam2392 I think the error is bc the repo name hasn't changed yet.. I think it should be fine once rename the repo itself? LMK what you think.

2024-07-07 22:14 UTC, adam2392 commented on README.md
> +Note that this package was originally named ``scikit-tree`` but was renamed to ``treeple`` after version 0.9.0. version <0.9.0 is still available at <https://pypi.org/project/scikit-tree/>.
This should state v0.8.0 as by v0.9.0 we will rename I suppose?

2024-07-07 22:16 UTC, adam2392 commented on .circleci/config.yml
> +              git remote add upstream https://github.com/neurodata/treeple.git;
```suggestion
              git remote add upstream https://github.com/neurodata/scikit-tree.git;
```

2024-07-07 23:27 UTC, adam2392 commented
@SUKI-O I think we can make that final change once we confirm the CI functions as expected. Seems like there are still some leftover warnings. You can try resolving locally too

2024-07-08 14:53 UTC, adam2392 requested changes
You need to rename the `sklearn_vs_sktree` folder under `examples/` to `sklearn_vs_treeple` to fix the CI error

2024-07-08 14:53 UTC, adam2392 commented on doc/whats_new/v0.9.rst
> +- |MNT| Rename the package to ``treeple``. By `SUKI-O`_ (:pr:`#292`)
```suggestion
- |API| Rename the package to ``treeple``. By `SUKI-O`_ (:pr:`#292`)
```

This is a major API change.

2024-07-08 14:53 UTC, adam2392 commented on doc/whats_new/v0.9.rst
Under `Version 0.9` title, you can add a sentence saying that the package was renamed to `treeple`, and therefore someone can replace

`import sktree` with `import treeple as tp`

and

`from sktree import ...` with `from treeple import …`
`from sktree… import ...` with `from treeple... import ...`

2024-07-09 14:09 UTC, adam2392 approved these changes
LGTM. Thanks @SUKI-O!

2024-07-09 14:09 UTC, merged