FIX remove regressor multi_label tag
neurodata/treeple pull request #339
Opened 2024-12-12 15:18 UTC by PSSF23

#### Reference Issues/PRs

#### What does this implement/fix? Explain your changes.

#### Any other comments?

2024-12-17 16:04 UTC, adam2392 approved these changes
LGTM

2024-12-17 16:04 UTC, adam2392 commented on treeple/tree/_classes.py
> +        # tags.regressor_tags.multi_label = True
Perhaps let's just add an inline comment saying "TODO: add regression support"?

2024-12-17 16:05 UTC, adam2392 requested changes
I think tho branch should get updated wrt main

2024-12-23 00:28 UTC, adam2392 commented on .github/workflows/build_wheels.yml
> +          - [macos-latest, macosx, x86_64]
For my education, why do we need this change?

2025-02-13 19:31 UTC, PSSF23 commented on .github/workflows/build_wheels.yml
> +          - [macos-latest, macosx, x86_64]
Sorry for late reply. It's due to the drop of support for the previous Mac version.

2025-02-13 19:34 UTC, merged

2025-02-13 19:34 UTC, PSSF23 commented
Merged for new changes on honest prune/kernel method #345